/**
 * Mock Feedback Data
 * Contains feedback/rating data for tutors
 */

export const mockFeedbacks = [
  {
    id: 1,
    tutor: "Nguyễn Văn A",
    student: "Trần Thị B",
    course: "Lập trình Web",
    rating: 5,
    comment: "Thầy dạy rất hay, dễ hiểu.",
    date: "2025-10-20",
  },
  {
    id: 2,
    tutor: "Nguyễn Văn A",
    student: "Lê Văn C",
    course: "Cấu trúc dữ liệu",
    rating: 4,
    comment: "Bài tập hơi khó nhưng thầy hỗ trợ nhiệt tình.",
    date: "2025-10-21",
  },
  {
    id: 3,
    tutor: "Trần Thị D",
    student: "Phạm Văn E",
    course: "Giải tích 1",
    rating: 3,
    comment: "Giảng hơi nhanh.",
    date: "2025-10-22",
  },
  {
    id: 4,
    tutor: "Nguyễn Văn A",
    student: "Hoàng Thị F",
    course: "Lập trình Web",
    rating: 5,
    comment: "Tuyệt vời!",
    date: "2025-10-23",
  },
  {
    id: 5,
    tutor: "Lê Văn G",
    student: "Ngô Văn H",
    course: "Vật lý đại cương",
    rating: 2,
    comment: "Ít bài tập thực hành.",
    date: "2025-10-24",
  },
  {
    id: 6,
    tutor: "Nguyễn Văn A",
    student: "Vũ Thị I",
    course: "Lập trình Web",
    rating: 5,
    comment: "Rất tâm huyết.",
    date: "2025-10-25",
  },
  {
    id: 7,
    tutor: "Trần Thị D",
    student: "Đinh Văn K",
    course: "Giải tích 1",
    rating: 4,
    comment: "Cô giảng chi tiết.",
    date: "2025-10-26",
  },
  {
    id: 8,
    tutor: "Lê Văn G",
    student: "Mai Thị L",
    course: "Vật lý đại cương",
    rating: 1,
    comment: "Không hiểu gì cả.",
    date: "2025-10-27",
  },
  {
    id: 9,
    tutor: "Nguyễn Văn A",
    student: "Bùi Văn M",
    course: "Cấu trúc dữ liệu",
    rating: 3,
    comment: "Bình thường.",
    date: "2025-10-28",
  },
  {
    id: 10,
    tutor: "Trần Thị D",
    student: "Đỗ Thị N",
    course: "Đại số tuyến tính",
    rating: 5,
    comment: "Cô dạy rất hay.",
    date: "2025-10-29",
  },
];
