/**
 * Mock Feedback Data
 * Contains feedback/rating data for tutors
 */

export const mockFeedbacks = [
  {
    id: 1,
    tutor: "Nguyễn Văn A",
    student: "Trần Thị B",
    course: "Lập trình Web",
    rating: 5,
    criteria: {
      teaching: 95,
      materials: 90,
      support: 100,
      facilities: 85,
    },
    comment: "Thầy dạy rất hay, dễ hiểu.",
    date: "2025-10-20",
  },
  {
    id: 2,
    tutor: "Nguyễn Văn A",
    student: "Lê Văn C",
    course: "Cấu trúc dữ liệu",
    rating: 4,
    criteria: {
      teaching: 80,
      materials: 85,
      support: 90,
      facilities: 80,
    },
    comment: "Bài tập hơi khó nhưng thầy hỗ trợ nhiệt tình.",
    date: "2025-10-21",
  },
  {
    id: 3,
    tutor: "Trần Thị D",
    student: "Phạm Văn E",
    course: "Giải tích 1",
    rating: 3,
    criteria: {
      teaching: 60,
      materials: 70,
      support: 60,
      facilities: 70,
    },
    comment: "Giảng hơi nhanh.",
    date: "2025-10-22",
  },
  {
    id: 4,
    tutor: "Nguyễn Văn A",
    student: "Hoàng Thị F",
    course: "Lập trình Web",
    rating: 5,
    criteria: {
      teaching: 100,
      materials: 95,
      support: 95,
      facilities: 90,
    },
    comment: "Tuyệt vời!",
    date: "2025-10-23",
  },
  {
    id: 5,
    tutor: "Lê Văn G",
    student: "Ngô Văn H",
    course: "Vật lý đại cương",
    rating: 2,
    criteria: {
      teaching: 40,
      materials: 50,
      support: 30,
      facilities: 60,
    },
    comment: "Ít bài tập thực hành.",
    date: "2025-10-24",
  },
  {
    id: 6,
    tutor: "Nguyễn Văn A",
    student: "Vũ Thị I",
    course: "Lập trình Web",
    rating: 5,
    criteria: {
      teaching: 98,
      materials: 92,
      support: 95,
      facilities: 88,
    },
    comment: "Rất tâm huyết.",
    date: "2025-10-25",
  },
  {
    id: 7,
    tutor: "Trần Thị D",
    student: "Đinh Văn K",
    course: "Giải tích 1",
    rating: 4,
    criteria: {
      teaching: 85,
      materials: 80,
      support: 85,
      facilities: 80,
    },
    comment: "Cô giảng chi tiết.",
    date: "2025-10-26",
  },
  {
    id: 8,
    tutor: "Lê Văn G",
    student: "Mai Thị L",
    course: "Vật lý đại cương",
    rating: 1,
    criteria: {
      teaching: 20,
      materials: 30,
      support: 20,
      facilities: 40,
    },
    comment: "Không hiểu gì cả.",
    date: "2025-10-27",
  },
  {
    id: 9,
    tutor: "Nguyễn Văn A",
    student: "Bùi Văn M",
    course: "Cấu trúc dữ liệu",
    rating: 3,
    criteria: {
      teaching: 70,
      materials: 75,
      support: 65,
      facilities: 70,
    },
    comment: "Bình thường.",
    date: "2025-10-28",
  },
  {
    id: 10,
    tutor: "Trần Thị D",
    student: "Đỗ Thị N",
    course: "Đại số tuyến tính",
    rating: 5,
    criteria: {
      teaching: 95,
      materials: 90,
      support: 95,
      facilities: 90,
    },
    comment: "Cô dạy rất hay.",
    date: "2025-10-29",
  },
];
