/**
 * Mock Library Data
 * Contains digital library materials and resources
 */

export const mockMaterials = [
  {
    id: 1,
    title: "Giáo trình Lập trình Web (Full)",
    course: "Lập trình Web",
    type: "PDF",
    author: "Khoa KH&KT MT",
    size: "15 MB",
    date: "2025-09-01",
    downloads: 1200,
  },
  {
    id: 2,
    title: "Slide Bài giảng Chương 1-5",
    course: "Lập trình Web",
    type: "Slide",
    author: "TS. Nguyễn Văn A",
    size: "45 MB",
    date: "2025-09-05",
    downloads: 850,
  },
  {
    id: 3,
    title: "Bộ đề Quiz Chương 1-5",
    course: "Cấu trúc dữ liệu",
    type: "Quiz",
    author: "Tutor Team",
    size: "2 MB",
    date: "2025-10-15",
    downloads: 3400,
  },
  {
    id: 4,
    title: "Video Record: Seminar AI 2025",
    course: "Trí tuệ nhân tạo",
    type: "Video",
    author: "CLB AI",
    size: "1.2 GB",
    date: "2025-08-20",
    downloads: 500,
  },
  {
    id: 5,
    title: "Bài tập lớn: Quản lý thư viện",
    course: "Cơ sở dữ liệu",
    type: "PDF",
    author: "Nhóm SV 1",
    size: "5 MB",
    date: "2025-11-01",
    downloads: 230,
  },
  {
    id: 6,
    title: "Slide Ôn tập tổng hợp",
    course: "Giải tích 1",
    type: "Slide",
    author: "Tutor Lê Vy",
    size: "12 MB",
    date: "2025-12-10",
    downloads: 1500,
  },
  {
    id: 7,
    title: "Ebook: Clean Code",
    course: "Công nghệ phần mềm",
    type: "PDF",
    author: "Robert C. Martin",
    size: "8 MB",
    date: "2025-01-15",
    downloads: 4500,
  },
  {
    id: 8,
    title: "Bộ Quiz Vật lý Đại cương",
    course: "Vật lý đại cương",
    type: "Quiz",
    author: "Tutor Team",
    size: "1.5 MB",
    date: "2025-06-20",
    downloads: 900,
  },
  {
    id: 9,
    title: "Hướng dẫn cài đặt Environment",
    course: "Hệ điều hành",
    type: "PDF",
    author: "Lab Center",
    size: "3 MB",
    date: "2025-09-10",
    downloads: 600,
  },
];
